name: Deploy to Ubuntu Server - Accounts

on:
  push:
    branches:
      - Accounts

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF_SSH'
            cd ~/BillBizz
            git checkout Accounts
            git pull

            # Remove only the old account-container if it exists
            if docker ps -a --format '{{.Names}}' | grep -q "^account-container$"; then
              echo "Removing old account-container..."
              docker rm -f account-container
            fi

            # Build the Docker image using an inline Dockerfile
            echo "Building the account-container image..."
            docker build -t account-container - <<EOF_DOCKER
FROM node:22.11.0
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 5001
CMD ["node", "server.js"]
EOF_DOCKER

            # Run the new container with the correct port mapping
            echo "Deploying the new account-container..."
            docker run -d --name account-container -p 5001:5001 account-container
          EOF_SSH
