name: Deploy Accounts Service to Ubuntu Server

on:
  push:
    branches:
      - Accounts  # Trigger on push to the 'Accounts' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy Accounts to Server
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            # Navigate to your project directory
            cd ~/BillBizz

            # Pull the latest code for the Accounts branch
            git checkout Accounts
            git pull origin Accounts

            # Stop and remove old containers (if any)
            docker stop account-container || true
            docker rm account-container || true

            # Build the Docker image for Accounts
            docker build -t account-container -f Dockerfile.accounts .

            # Run the new container for Accounts
            docker run -d --name account-container -p 5001:5001 account-container
          EOF
