name: Deploy to Ubuntu Server - Accounts

on:
  push:
    branches:
      - Accounts

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF_SSH'
            cd ~/BillBizz
            git pull origin Accounts

            # Check if the container is already running, and stop & remove if it exists
            if docker ps -q -f name=account-container; then
              echo "Stopping and removing old account-container..."
              docker stop account-container
              docker rm account-container
            fi

            # Build the Docker image using an inline Dockerfile
            echo "Building the account-container image..."
            docker build -t account-container - <<'EOF_DOCKER'
            FROM node:22.11.0
            WORKDIR /usr/src/app
            COPY package*.json ./
            RUN npm install
            COPY . .
            EXPOSE 5002
            CMD ["node", "server.js"]
            'EOF_DOCKER'

            # Run the new container with the correct port
            echo "Deploying the new account-container..."
            docker run -d --name account-container -p 5002:5002 account-container
         'EOF_SSH'
