name: Deploy to Hostinger FTP

on:
  push:
    branches:
      - dist  # Trigger on push to the `dist` branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: dist  # Ensure it works on the `dist` branch

      - name: Delete All Files on FTP Server and Deploy New Files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: "${{ secrets.FTP_SERVER }}"  # Securely using GitHub Secret
          username: "${{ secrets.FTP_USERNAME }}"
          password: "${{ secrets.FTP_PASSWORD }}"
          local-dir: "./"  # Folder in your repo that you want to upload
          server-dir: "/public_html/"  # Deploy to `/public_html/` directory
          dangerous-clean-slate: true  # Deletes all files in the server directory before uploading new ones
