name: Deploy to Ubuntu Server - Customers

on:
  push:
    branches:
      - Customers

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd ~/BillBizz
            git pull origin Accounts

            # Check if the container is already running, and stop & remove if it exists
            if docker ps -q -f name=Customers-container; then
              echo "Stopping and removing old Customers-container..."
              docker stop Customers-container
              docker rm Customers-container
            fi

            # Build the Docker image using the updated Dockerfile
            echo "Building the Customers-container image..."
            docker build -t Customers-container -f Dockerfile .

            # Run the new container with the correct port
            echo "Deploying the new Customers-container..."
            docker run -d --name Customers-container -p 5002:5002 Customers-container
          EOF
