name: Deploy to Ubuntu Server - All Branches

on:
  push:
    branches:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd ~/BillBizz
            git pull origin ${{ github.ref_name }}

            # Check if the container is already running, and stop & remove if it exists
            if docker ps -q -f name=${{ github.ref_name }}-container; then
              echo "Stopping and removing old ${{ github.ref_name }}-container..."
              docker stop ${{ github.ref_name }}-container
              docker rm ${{ github.ref_name }}-container
            fi

            # Build the Docker image using the updated Dockerfile
            echo "Building the ${{ github.ref_name }}-container image..."
            docker build -t ${{ github.ref_name }}-container -f Dockerfile .

            # Run the new container with the correct port
            echo "Deploying the new ${{ github.ref_name }}-container..."
            docker run -d --name ${{ github.ref_name }}-container -p 5001:5001 ${{ github.ref_name }}-container
          EOF
